version: "3"
services:
  code-server:
    container_name: code-server
    volumes:
      - ${PWD}/data/codeserver/workspace:/home/workspace
      - ${PWD}/data/codeserver/config:/config
    env_file:
      - ${PWD}/.env
    restart: unless-stopped
    expose:
      - "8443"
    image: lscr.io/linuxserver/code-server:4.92.2
  vaultwarden: 
    container_name: vaultwarden
    volumes:
      - ${PWD}/data/vaultwarden/data:/data/
    restart: unless-stopped
    expose:
      - "80"
    image: vaultwarden/server:1.32.0-alpine
  portainer-ce:
    expose:
      - "9443"
    container_name: portainer
    command: --sslcert /certs/local.portainer-crt.pem --sslkey /certs/local.portainer-key.pem
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PWD}/data/portainer:/data
      - ${PWD}/data/nginx/certs/local.portainer-crt.pem:/certs/local.portainer-crt.pem
      - ${PWD}/data/nginx/certs/local.portainer-key.pem:/certs/local.portainer-key.pem
    image: portainer/portainer-ce:2.21.1-alpine
  nginx-app:
    container_name: nginx
    restart: unless-stopped
    volumes: 
      - ${PWD}/data/nginx/certs:/etc/nginx/certs
      - ${PWD}/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    depends_on:
      - code-server
      - vaultwarden
    image: nginx:1.27.1