version: "3"
services:
  code-server:
    container_name: code-server
    volumes:
      - ${PWD}/data/codeserver/workspace:/home/workspace
      - ${PWD}/data/codeserver/config:/config
    env_file:
      - ${PWD}/.env
    restart: unless-stopped
    expose:
      - "8443"
    image: lscr.io/linuxserver/code-server:4.92.2
  vaultwarden: 
    container_name: vaultwarden
    volumes:
      - ${PWD}/data/vaultwarden/data:/data/
    restart: unless-stopped
    expose:
      - "80"
    image: vaultwarden/server:1.32.0-alpine
  nginx-app:
    container_name: nginx
    restart: unless-stopped
    volumes: 
      - ${PWD}/data/nginx/certs:/etc/nginx/certs
      - ${PWD}/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    depends_on:
      - code-server
      - vaultwarden
    image: nginx:1.27.1