version: "3.7"
services:
  code-server:
    container_name: code-server
    volumes:
      - ${PWD}/data/codeserver/workspace:/home/workspace
      - ${PWD}/data/codeserver/config:/config
    env_file:
      - ${PWD}/.env-codeserver
    restart: unless-stopped
    expose:
      - "8443"
    image: lscr.io/linuxserver/code-server:4.92.2
  vaultwarden: 
    container_name: vaultwarden
    env_file:
      - ${PWD}/.env-vaultwarden
    volumes:
      - ${PWD}/data/vaultwarden/data:/data/
    restart: unless-stopped
    expose:
      - "80"
    image: vaultwarden/server:1.32.0-alpine
  portainer-ce:
    expose:
      - "9443"
    container_name: portainer
    command: --sslcert /certs/local.portainer-crt.pem --sslkey /certs/local.portainer-key.pem
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PWD}/data/portainer:/data
      - ${PWD}/data/nginx/certs/local.portainer-crt.pem:/certs/local.portainer-crt.pem
      - ${PWD}/data/nginx/certs/local.portainer-key.pem:/certs/local.portainer-key.pem
    image: portainer/portainer-ce:2.21.1-alpine
  postgres:
    container_name: postgre-db
    restart: unless-stopped
    volumes:
      - postgre_data:/var/lib/postgresql/data
    ports:
      - 15432:5432
    expose:
      - "5432"
    env_file:
      - ${PWD}/.env-vaultwarden
    image: postgres:16.4
  nextcloud:
    container_name: nextcloud
    restart: unless-stopped
    expose:
      - "9000"
    volumes:
      - nextcloud_data:/var/www/html
    environment:
      - POSTGRES_HOST=postgres
    env_file:
      - ${PWD}/.env-nextcloud
    depends_on:
      - postgres
    image: nextcloud:28.0.9-fpm
  webtop:
    container_name: webtop
    restart: unless-stopped
    image: lscr.io/linuxserver/webtop:amd64-ubuntu-kde
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jakarta
      - SUBFOLDER=/
      - TITLE=local.Webtop
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - webtop_config:/config
    expose:
      - "3000"
    devices: 
      - /dev/dri:/dev/dri
    shm_size: "1gb"
    security_opt:
      - seccomp:unconfined
  nginx-prometheus-exporter:
    container_name: nginx-exporter
    image: nginx/nginx-prometheus-exporter:1.3.0
    restart: unless-stopped
    command: --nginx.scrape-uri=http://nginx-app:8080/stub_status
    expose:
      - "9113"
  prometheus:
    container_name: prometheus
    restart: unless-stopped
    expose:
      - "9090"
    volumes:
      - ${PWD}/data/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    image: prom/prometheus:v2.54.1
  nginx-app:
    container_name: nginx
    restart: unless-stopped
    volumes: 
      - ${PWD}/data/nginx/certs:/etc/nginx/certs
      - ${PWD}/nginx/nginx.conf:/etc/nginx/nginx.conf
      # should mount the nextcloud data since fastcgi.
      - nextcloud_data:/var/www/html
    ports:
      - 80:80
      - 443:443
    expose:
      - "8080"
    depends_on:
      - code-server
      - vaultwarden
      - nextcloud
    image: nginx:1.27.1
volumes:
  postgre_data:
  nextcloud_data:
  webtop_config: